name: smart_charge
description: "智能充电桩导航App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 地图 - 高德官方 Flutter SDK
  amap_flutter_map: 3.0.0
  amap_flutter_base: 3.0.0
  latlong2: ^0.9.1

  # 状态管理
  provider: ^6.1.1

  # 网络请求
  dio: ^5.4.0

  # 打开URL（导航）
  url_launcher: ^6.2.4

  # 权限请求
  permission_handler: ^11.3.0

  # 定位
  geolocator: 14.0.0
  geolocator_android: ^4.4.1

  # 本地存储
  shared_preferences: ^2.2.2
  flutter_compass: ^0.8.1
  amap_flutter_location: ^3.0.0

dependency_overrides:
  geolocator_android: 4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/app_icon_fg.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/station_icon.png
    - assets/station_icon_sel.png
    - assets/user_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
